export const ActionType = {
  //MODAL HANDLER
  HANDLE_MODAL_OPEN: 'HANDLE_MODAL_OPEN',
  HANDLE_MODAL_CLOSE: 'HANDLE_MODAL_CLOSE',

  // FETCH FILMS
  FETCH_FILMS_REQUEST : 'FETCH_FILMS_REQUEST',
  FETCH_FILMS_SUCCESS : 'FETCH_FILMS_SUCCESS',
  FETCH_FILMS_ERROR : 'FETCH_FILMS_ERROR',

  //FETCH PLANETS
  FETCH_PLANETS_BY_ID_REQUEST: 'FETCH_PLANETS_BY_ID_REQUEST',
  FETCH_PLANETS_BY_ID_SUCCESS: 'FETCH_PLANETS_BY_ID_SUCCESS',
  FETCH_PLANETS_BY_ID_ERROR: 'FETCH_PLANETS_BY_ID_ERROR',

  //FETCH STARSHIPS
  FETCH_STARSHIPS_BY_ID_REQUEST: 'FETCH_STARSHIPS_BY_ID_REQUEST',
  FETCH_STARSHIPS_BY_ID_SUCCESS: 'FETCH_STARSHIPS_BY_ID_SUCCESS',
  FETCH_STARSHIPS_BY_ID_ERROR: 'FETCH_STARSHIPS_BY_ID_ERROR',

  //FETCH VEHICLES
  FETCH_VEHICLES_BY_ID_REQUEST: 'FETCH_VEHICLES_BY_ID_REQUEST',
  FETCH_VEHICLES_BY_ID_SUCCESS: 'FETCH_VEHICLES_BY_ID_SUCCESS',
  FETCH_VEHICLES_BY_ID_ERROR: 'FETCH_VEHICLES_BY_ID_ERROR',

  //FETCH SPECIES
  FETCH_SPECIES_BY_ID_REQUEST: 'FETCH_SPECIES_BY_ID_REQUEST',
  FETCH_SPECIES_BY_ID_SUCCESS: 'FETCH_SPECIES_BY_ID_SUCCESS',
  FETCH_SPECIES_BY_ID_ERROR: 'FETCH_SPECIES_BY_ID_ERROR',

  //FETCH PEOPLE
  FETCH_PEOPLE_BY_ID_REQUEST: 'FETCH_PEOPLE_BY_ID_REQUEST',
  FETCH_PEOPLE_BY_ID_SUCCESS: 'FETCH_PEOPLE_BY_ID_SUCCESS',
  FETCH_PEOPLE_BY_ID_ERROR: 'FETCH_PEOPLE_BY_ID_ERROR',

  //PAGINATION PEOPLE
  FETCH_PAGINATION_PEOPLE_REQUEST : 'FETCH_PAGINATION_PEOPLE_REQUEST',
  FETCH_PAGINATION_PEOPLE_SUCCESS : 'FETCH_PAGINATION_PEOPLE_SUCCESS',
  FETCH_PAGINATION_PEOPLE_ERROR : 'FETCH_PAGINATION_PEOPLE_ERROR',

  //PAGINATION PEOPLE
  FETCH_PAGINATION_PLANETS_REQUEST : 'FETCH_PAGINATION_PLANETS_REQUEST',
  FETCH_PAGINATION_PLANETS_SUCCESS : 'FETCH_PAGINATION_PLANETS_SUCCESS',
  FETCH_PAGINATION_PLANETS_ERROR : 'FETCH_PAGINATION_PLANETS_ERROR',

  //PAGINATION SPECIES
  FETCH_PAGINATION_SPECIES_REQUEST : 'FETCH_PAGINATION_SPECIES_REQUEST',
  FETCH_PAGINATION_SPECIES_SUCCESS : 'FETCH_PAGINATION_SPECIES_SUCCESS',
  FETCH_PAGINATION_SPECIES_ERROR : 'FETCH_PAGINATION_SPECIES_ERROR',

  //PAGINATION STARSHIPS
  FETCH_PAGINATION_STARSHIPS_REQUEST : 'FETCH_PAGINATION_STARSHIPS_REQUEST',
  FETCH_PAGINATION_STARSHIPS_SUCCESS : 'FETCH_PAGINATION_STARSHIPS_SUCCESS',
  FETCH_PAGINATION_STARSHIPS_ERROR : 'FETCH_PAGINATION_STARSHIPS_ERROR',


  //PAGINATION VEHICLES
  FETCH_PAGINATION_VEHICLES_REQUEST : 'FETCH_PAGINATION_VEHICLES_REQUEST',
  FETCH_PAGINATION_VEHICLES_SUCCESS : 'FETCH_PAGINATION_VEHICLES_SUCCESS',
  FETCH_PAGINATION_VEHICLES_ERROR : 'FETCH_PAGINATION_VEHICLES_ERROR',
};